micronaut:
  application:
    name: micronautDatabaseAuthentication
---
netty:
  default:
    allocator:
      max-order: 3
---
micronaut:
  security:
    authentication: cookie
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}
    redirect:
      unauthorized:
        url: '/auth'
      login-success: '/'
---
datasources:
  default:
    driverClassName: com.mysql.cj.jdbc.Driver
    db-type: mysql
    schema-generate: CREATE_DROP
    dialect: MYSQL